use std::sync::OnceLock;
use regex::Regex;

pub struct CompiledRegexes {
    pub cred_pair: Regex,
    pub pass_standalone: Regex,
    pub api_keys: Regex,
    pub bearer: Regex,
    pub jwt: Regex,
    pub ssh_key: Regex,
    pub privkey: Regex,
    pub cc_spaced: Regex,
    pub cc_raw: Regex,
    pub routing: Regex,
    pub iban: Regex,
    pub swift: Regex,
    pub account: Regex,
    pub sort_code: Regex,
    pub btc_legacy: Regex,
    pub btc_bech32: Regex,
    pub eth: Regex,
    pub tron: Regex,
    pub sol: Regex,
    pub ltc: Regex,
    pub doge: Regex,
    pub xmr: Regex,
    pub crypto_uri: Regex,
    pub ssn: Regex,
    pub passport: Regex,
    pub driver_lic: Regex,
    pub ein: Regex,
    #[allow(dead_code)]
    pub street_addr: Regex,
    pub hotel_conf: Regex,
    #[allow(dead_code)]
    pub gps: Regex,
    pub weapons: Regex,
    pub narcotics: Regex,
    pub explosives: Regex,
    pub terrorism: Regex,
    pub cve: Regex,
    pub c2: Regex,
    pub confidential: Regex,
    pub nda: Regex,
    pub phish_cred: Regex,
    pub phish_finance: Regex,
    pub phone_intl: Regex,
    pub phone_contextual: Regex,
    pub phone_national: Regex,
    pub phone_raw_prefix: Regex,
    pub vcard_block: Regex,
}

static REGEXES: OnceLock<CompiledRegexes> = OnceLock::new();

pub fn get_regexes() -> &'static CompiledRegexes {
    REGEXES.get_or_init(|| {
        CompiledRegexes {
            cred_pair: Regex::new(r"(?i)(?:username|user|login|email)[:=\s]+([a-zA-Z0-9._%+\-@]{3,50})\s+(?:password|pwd|pass)[:=\s]+([^\s,;]{4,50})").unwrap(),
            pass_standalone: Regex::new(r"(?i)(?:password|passwd|passcode|secret\s*key)[:=\s]+([^\s,;]{6,60})").unwrap(),
            api_keys: Regex::new(r"\b(AKIA[0-9A-Z]{16}|sk_live_[0-9a-zA-Z]{24,40}|ghp_[0-9a-zA-Z]{36}|AIza[0-9A-Za-z\-_]{35})\b").unwrap(),
            bearer: Regex::new(r"Bearer\s+([A-Za-z0-9\-\._~\+\/]{25,}=*)").unwrap(),
            jwt: Regex::new(r"(eyJ[A-Za-z0-9-_=]{15,}\.[A-Za-z0-9-_=]{15,}\.[A-Za-z0-9-_.+/=]{10,})").unwrap(),
            ssh_key: Regex::new(r"-----BEGIN (?:RSA|DSA|EC|OPENSSH) PRIVATE KEY-----").unwrap(),
            privkey: Regex::new(r"(?i)(?:private\s*key|privkey)[:=\s]+([0-9a-fA-F]{64})\b").unwrap(),
            cc_spaced: Regex::new(r"\b((?:4[0-9]{3}|5[1-5][0-9]{2}|6011|3[47][0-9]{2})[\s\-][0-9]{4}[\s\-][0-9]{4}[\s\-][0-9]{4})\b").unwrap(),
            cc_raw: Regex::new(r"\b(4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6011[0-9]{12})\b").unwrap(),
            routing: Regex::new(r"(?i)(?:routing(?:\s*number|#)?|aba(?:\s*#|\s*no)?)\s*[:#=]?\s*(\b(?:0[1-9]|[123][0-9]|6[1-9]|7[0-2]|80)\d{7}\b)").unwrap(),
            iban: Regex::new(r"(?i)(?:iban)\s*[:#=]?\s*([A-Z]{2}[0-9]{2}[A-Z0-9]{4}[0-9]{7}(?:[A-Z0-9]?){0,16})\b").unwrap(),
            swift: Regex::new(r"(?i)(?:swift(?:\s*code|\s*bic)?|bic(?:\s*code)?|swift/bic)\s*[:#=]?\s*([A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?)\b").unwrap(),
            account: Regex::new(r"(?i)(?:bank\s*account(?:\s*number|\s*#)?|acct(?:\s*number|\s*#))\s*[:#=]?\s*([0-9]{8,17})\b").unwrap(),
            sort_code: Regex::new(r"(?i)(?:sort\s*code|sort-code|sortcode)\s*[:#=]?\s*(\d{2}[-\s]?\d{2}[-\s]?\d{2})\b").unwrap(),
            btc_legacy: Regex::new(r"\b([13][a-km-zA-HJ-NP-Z1-9]{25,34})\b").unwrap(),
            btc_bech32: Regex::new(r"\b(bc1[a-zA-HJ-NP-Z0-9]{39,59})\b").unwrap(),
            eth: Regex::new(r"\b(0x[a-fA-F0-9]{40})\b").unwrap(),
            tron: Regex::new(r"\b(T[A-Za-z1-9]{33})\b").unwrap(),
            sol: Regex::new(r"\b([1-9A-HJ-NP-Za-km-z]{32,44})\b").unwrap(),
            ltc: Regex::new(r"\b([LM3][a-km-zA-HJ-NP-Z1-9]{25,34})\b").unwrap(),
            doge: Regex::new(r"\b(D[A-Za-z1-9]{33})\b").unwrap(),
            xmr: Regex::new(r"\b(4[0-9AB][1-9A-HJ-NP-Za-km-z]{93})\b").unwrap(),
            crypto_uri: Regex::new(r"(?i)\b((?:bitcoin|ethereum|litecoin|doge|solana|monero):[a-zA-Z0-9?=_&%-]+)\b").unwrap(),
            ssn: Regex::new(r"\b(\d{3}-\d{2}-\d{4})\b").unwrap(),
            passport: Regex::new(r"(?i)(?:passport(?:\s*#|\s*no|\s*number)?)\s*[:#=]?\s*([A-PR-WYa-pr-wy][0-9]{7,8})\b").unwrap(),
            driver_lic: Regex::new(r"(?i)(?:driver'?s?\s*license|driving\s*licence)\s*(?:#|no|number)?[:=\s]*([A-Z0-9]{6,14})\b").unwrap(),
            ein: Regex::new(r"(?i)(?:ein|federal\s*tax\s*id)\s*[:#=]?\s*(\d{2}-\d{7})\b").unwrap(),
            street_addr: Regex::new(r"\b([0-9]{1,5}\s+[A-Z][a-zA-Z0-9.,]{1,20}(?:\s+[A-Z][a-zA-Z0-9.,]{1,20}){1,3}\s+(?:Street|St\.|Avenue|Ave\.|Road|Rd\.|Boulevard|Blvd\.|Lane|Ln\.|Drive|Dr\.|Way|Court|Ct\.|Parkway|Pkwy))\b").unwrap(),
            hotel_conf: Regex::new(r"(?i)(?:hotel|lodging|flight)\s*(?:confirmation|booking|reservation)\s*(?:#|no|number)?[:=\s]*([A-Z0-9]{6,12})\b").unwrap(),
            gps: Regex::new(r"\b(-?[0-9]{1,2}\.[0-9]{4,8}\s*,\s*-?[0-9]{1,3}\.[0-9]{4,8})\b").unwrap(),
            weapons: Regex::new(r"(?i)\b(glock|beretta|ar-15|ak-47|silencer|ghost\s*gun|auto\s*sear|firearm|pistol|carbine|smg|shotgun|rifle|revolver)\b").unwrap(),
            narcotics: Regex::new(r"(?i)\b(cocaine|coke|heroin|fentanyl|methamphetamine|crystal\s*meth|mdma|ecstasy|oxycodone|percocet|xanax|alprazolam|ketamine)\b").unwrap(),
            explosives: Regex::new(r"(?i)\b(bomb|explosive|detonator|c4|ied|suicide\s*vest|pipe\s*bomb|anthrax|ricin|poison)\b").unwrap(),
            terrorism: Regex::new(r"(?i)\b(al-qaeda|al-qa'ida|boko\s*haram|hezbollah|hamas|jihadist|suicide\s*bomber|terrorist\s*cell|taliban)\b").unwrap(),
            cve: Regex::new(r"(CVE-\d{4}-\d{4,7})").unwrap(),
            c2: Regex::new(r"(?i)\b(command\s*and\s*control|c2\s*server|c&c\s*server|reverse\s*shell|meterpreter)\b").unwrap(),
            confidential: Regex::new(r"(?i)\b(strictly\s+confidential|attorney[- ]client\s+privilege|privileged\s*and\s*confidential|work\s*product\s*doctrine)\b").unwrap(),
            nda: Regex::new(r"(?i)\b(non[- ]disclosure\s*agreement|\bnda\b|proprietary\s+and\s+confidential)\b").unwrap(),
            phish_cred: Regex::new(r"(?i)\b(verify\s*your\s*identity|confirm\s*your\s*password|update\s*your\s*account\s*credentials)\b").unwrap(),
            phish_finance: Regex::new(r"(?i)\b(wire\s*transfer\s*urgently|urgent\s*wire\s*payment|purchase\s*gift\s*cards)\b").unwrap(),
            phone_intl: Regex::new(r"(?:\+|00)([1-9]\d{0,3})[\s\-\/]?\(?(\d{2,4})\)?[\s\-\/]?(\d{3,4})[\s\-\/]?(\d{3,6})\b").unwrap(),
            phone_contextual: Regex::new(r"(?i)(?:tel|telephone|phone|mobile|cell|direct|office|work|fax|whatsapp|ph|contact)[\s\.:#\-]+(?:\+?([0-9\s\(\)\-\/]{7,25}))").unwrap(),
            phone_national: Regex::new(r"\b(0[1-9]\d{1,3}[\s\.\-\/]?\d{3,4}[\s\.\-\/]?\d{3,4})\b").unwrap(),
            phone_raw_prefix: Regex::new(r"\b(234\d{10}|44\d{10}|971\d{8,9}|91\d{10}|86\d{11}|49\d{10,11}|33\d{9}|1\d{10})\b").unwrap(),
            vcard_block: Regex::new(r"(?is)BEGIN:VCARD(.*?)END:VCARD").unwrap(),
        }
    })
}

pub struct AppSignature {
    pub name: &'static str,
    pub domain_id: &'static str,
    pub subcategory: &'static str,
    pub keywords: &'static [&'static str],
    pub category_title: &'static str,
}

pub static APP_SIGNATURES: &[AppSignature] = &[
    // 🌐 SOCIAL MEDIA & COMMUNITIES
    AppSignature { name: "Snapchat", domain_id: "social_media", subcategory: "snapchat", keywords: &["snapchat.com", "sc-corp.com", "team snapchat"], category_title: "Social Media (Snapchat)" },
    AppSignature { name: "Twitter / X", domain_id: "social_media", subcategory: "twitter_x", keywords: &["twitter.com", "x.com", "api.twitter.com", "twittermail.com"], category_title: "Social Network (Twitter/X)" },
    AppSignature { name: "Instagram", domain_id: "social_media", subcategory: "instagram", keywords: &["instagram.com", "instagr.am", "mail.instagram.com"], category_title: "Social Network (Instagram)" },
    AppSignature { name: "Facebook", domain_id: "social_media", subcategory: "facebook", keywords: &["facebook.com", "fb.com", "facebookmail.com"], category_title: "Social Network (Facebook)" },
    AppSignature { name: "TikTok", domain_id: "social_media", subcategory: "tiktok", keywords: &["tiktok.com", "byteoversea.com", "tiktokmail.com"], category_title: "Social Video (TikTok)" },
    AppSignature { name: "LinkedIn", domain_id: "social_media", subcategory: "linkedin", keywords: &["linkedin.com", "linkedinmail.com"], category_title: "Professional Network (LinkedIn)" },
    AppSignature { name: "Reddit", domain_id: "social_media", subcategory: "reddit", keywords: &["reddit.com", "redditmail.com"], category_title: "Social Community (Reddit)" },
    AppSignature { name: "Pinterest", domain_id: "social_media", subcategory: "pinterest", keywords: &["pinterest.com", "pinterestmail.com"], category_title: "Social Platform (Pinterest)" },
    AppSignature { name: "YouTube", domain_id: "social_media", subcategory: "youtube", keywords: &["youtube.com", "youtu.be"], category_title: "Video Platform (YouTube)" },
    AppSignature { name: "Twitch", domain_id: "social_media", subcategory: "twitch", keywords: &["twitch.tv"], category_title: "Live Streaming (Twitch)" },
    AppSignature { name: "Tumblr", domain_id: "social_media", subcategory: "tumblr", keywords: &["tumblr.com"], category_title: "Social Blog (Tumblr)" },
    AppSignature { name: "Threads", domain_id: "social_media", subcategory: "threads", keywords: &["threads.net"], category_title: "Social Network (Threads)" },
    AppSignature { name: "Bluesky", domain_id: "social_media", subcategory: "bluesky", keywords: &["bsky.app", "bsky.social"], category_title: "Social Network (Bluesky)" },
    AppSignature { name: "VKontakte", domain_id: "social_media", subcategory: "vk", keywords: &["vk.com", "vkontakte.ru"], category_title: "Social Network (VKontakte)" },

    // 💬 MESSAGING & ENCRYPTED CHAT
    AppSignature { name: "Telegram", domain_id: "messaging_apps", subcategory: "telegram", keywords: &["telegram.org", "t.me", "telegram messenger"], category_title: "Encrypted Messenger (Telegram)" },
    AppSignature { name: "Signal", domain_id: "messaging_apps", subcategory: "signal", keywords: &["signal.org", "signal.me", "signal messenger"], category_title: "Private Messenger (Signal)" },
    AppSignature { name: "WhatsApp", domain_id: "messaging_apps", subcategory: "whatsapp", keywords: &["whatsapp.com", "wa.me", "whatsapp business"], category_title: "Messaging App (WhatsApp)" },
    AppSignature { name: "Discord", domain_id: "messaging_apps", subcategory: "discord", keywords: &["discord.com", "discord.gg", "discordapp.com"], category_title: "Chat Platform (Discord)" },
    AppSignature { name: "Session", domain_id: "messaging_apps", subcategory: "session", keywords: &["getsession.org", "session messenger"], category_title: "Anonymous Chat (Session)" },
    AppSignature { name: "Threema", domain_id: "messaging_apps", subcategory: "threema", keywords: &["threema.ch", "threema id"], category_title: "Secure Messenger (Threema)" },
    AppSignature { name: "Wickr", domain_id: "messaging_apps", subcategory: "wickr", keywords: &["wickr.com", "wickr me"], category_title: "Ephemeral Chat (Wickr)" },
    AppSignature { name: "Element / Matrix", domain_id: "messaging_apps", subcategory: "matrix", keywords: &["element.io", "matrix.org"], category_title: "Matrix Protocol (Element)" },
    AppSignature { name: "Viber", domain_id: "messaging_apps", subcategory: "viber", keywords: &["viber.com"], category_title: "Messaging App (Viber)" },
    AppSignature { name: "WeChat", domain_id: "messaging_apps", subcategory: "wechat", keywords: &["wechat.com", "weixin.qq.com"], category_title: "Messaging App (WeChat)" },
    AppSignature { name: "Line", domain_id: "messaging_apps", subcategory: "line", keywords: &["line.me", "naver.jp"], category_title: "Messaging App (Line)" },
    AppSignature { name: "Skype", domain_id: "messaging_apps", subcategory: "skype", keywords: &["skype.com", "skype.net"], category_title: "VoIP & Chat (Skype)" },
    AppSignature { name: "Kik", domain_id: "messaging_apps", subcategory: "kik", keywords: &["kik.com"], category_title: "Messaging App (Kik)" },

    // 🪙 CRYPTO PLATFORMS, EXCHANGES & WEB3
    AppSignature { name: "Binance", domain_id: "crypto_platforms", subcategory: "binance", keywords: &["binance.com", "binance exchange", "binance verification"], category_title: "Crypto Exchange (Binance)" },
    AppSignature { name: "Coinbase", domain_id: "crypto_platforms", subcategory: "coinbase", keywords: &["coinbase.com", "coinbase pro", "coinbase commerce"], category_title: "Crypto Platform (Coinbase)" },
    AppSignature { name: "Kraken", domain_id: "crypto_platforms", subcategory: "kraken", keywords: &["kraken.com", "kraken exchange"], category_title: "Crypto Exchange (Kraken)" },
    AppSignature { name: "KuCoin", domain_id: "crypto_platforms", subcategory: "kucoin", keywords: &["kucoin.com", "kucoin exchange"], category_title: "Crypto Exchange (KuCoin)" },
    AppSignature { name: "MetaMask", domain_id: "crypto_platforms", subcategory: "metamask", keywords: &["metamask.io", "metamask wallet"], category_title: "Crypto Wallet (MetaMask)" },
    AppSignature { name: "Trust Wallet", domain_id: "crypto_platforms", subcategory: "trust_wallet", keywords: &["trustwallet.com", "trust wallet"], category_title: "Crypto Wallet (Trust Wallet)" },
    AppSignature { name: "Ledger", domain_id: "crypto_platforms", subcategory: "ledger", keywords: &["ledger.com", "ledger live"], category_title: "Hardware Wallet (Ledger)" },
    AppSignature { name: "Trezor", domain_id: "crypto_platforms", subcategory: "trezor", keywords: &["trezor.io", "trezor suite"], category_title: "Hardware Wallet (Trezor)" },
    AppSignature { name: "Bybit", domain_id: "crypto_platforms", subcategory: "bybit", keywords: &["bybit.com", "bybit exchange"], category_title: "Crypto Exchange (Bybit)" },
    AppSignature { name: "OKX", domain_id: "crypto_platforms", subcategory: "okx", keywords: &["okx.com", "okex.com"], category_title: "Crypto Exchange (OKX)" },
    AppSignature { name: "Bitfinex", domain_id: "crypto_platforms", subcategory: "bitfinex", keywords: &["bitfinex.com"], category_title: "Crypto Exchange (Bitfinex)" },
    AppSignature { name: "Uniswap", domain_id: "crypto_platforms", subcategory: "uniswap", keywords: &["uniswap.org"], category_title: "DeFi DEX (Uniswap)" },
    AppSignature { name: "Phantom", domain_id: "crypto_platforms", subcategory: "phantom", keywords: &["phantom.app", "phantom wallet"], category_title: "Solana Wallet (Phantom)" },
    AppSignature { name: "Exodus", domain_id: "crypto_platforms", subcategory: "exodus", keywords: &["exodus.com", "exodus wallet"], category_title: "Crypto Wallet (Exodus)" },
    AppSignature { name: "Paxful", domain_id: "crypto_platforms", subcategory: "paxful", keywords: &["paxful.com", "paxful p2p"], category_title: "P2P Crypto (Paxful)" },
    AppSignature { name: "Gemini", domain_id: "crypto_platforms", subcategory: "gemini", keywords: &["gemini.com", "gemini exchange"], category_title: "Crypto Exchange (Gemini)" },
    AppSignature { name: "OpenSea", domain_id: "crypto_platforms", subcategory: "opensea", keywords: &["opensea.io"], category_title: "NFT Marketplace (OpenSea)" },
    AppSignature { name: "BitMEX", domain_id: "crypto_platforms", subcategory: "bitmex", keywords: &["bitmex.com"], category_title: "Crypto Derivatives (BitMEX)" },

    // ❤️ DATING & ROMANCE PLATFORMS
    AppSignature { name: "Tinder", domain_id: "dating_apps", subcategory: "tinder", keywords: &["gotinder.com", "tinder.com"], category_title: "Dating App (Tinder)" },
    AppSignature { name: "Bumble", domain_id: "dating_apps", subcategory: "bumble", keywords: &["bumble.com"], category_title: "Dating App (Bumble)" },
    AppSignature { name: "Hinge", domain_id: "dating_apps", subcategory: "hinge", keywords: &["hinge.co"], category_title: "Dating App (Hinge)" },
    AppSignature { name: "Badoo", domain_id: "dating_apps", subcategory: "badoo", keywords: &["badoo.com"], category_title: "Dating App (Badoo)" },
    AppSignature { name: "Grindr", domain_id: "dating_apps", subcategory: "grindr", keywords: &["grindr.com"], category_title: "Dating App (Grindr)" },
    AppSignature { name: "Match.com", domain_id: "dating_apps", subcategory: "match", keywords: &["match.com"], category_title: "Dating Service (Match.com)" },
    AppSignature { name: "OkCupid", domain_id: "dating_apps", subcategory: "okcupid", keywords: &["okcupid.com"], category_title: "Dating App (OkCupid)" },
    AppSignature { name: "Ashley Madison", domain_id: "dating_apps", subcategory: "ashley_madison", keywords: &["ashleymadison.com"], category_title: "Discreet Dating (Ashley Madison)" },
    AppSignature { name: "OnlyFans", domain_id: "dating_apps", subcategory: "onlyfans", keywords: &["onlyfans.com"], category_title: "Subscription Platform (OnlyFans)" },
    AppSignature { name: "Fansly", domain_id: "dating_apps", subcategory: "fansly", keywords: &["fansly.com"], category_title: "Subscription Platform (Fansly)" },

    // 🏦 FINTECH, COMMERCIAL BANKS & PAYMENTS
    AppSignature { name: "Huntington Bank", domain_id: "fintech_banking", subcategory: "huntington", keywords: &["huntington.com", "email.huntington.com", "huntingtononline"], category_title: "Commercial Bank (Huntington Bank)" },
    AppSignature { name: "Chase Bank / JPMorgan", domain_id: "fintech_banking", subcategory: "chase", keywords: &["chase.com", "emailonline.chase.com", "chaseonline"], category_title: "Commercial Bank (Chase)" },
    AppSignature { name: "Simmons Bank", domain_id: "fintech_banking", subcategory: "simmons", keywords: &["simmonsbank.com"], category_title: "Commercial Bank (Simmons Bank)" },
    AppSignature { name: "Armed Forces Bank", domain_id: "fintech_banking", subcategory: "afbank", keywords: &["afbank.com"], category_title: "Military Bank (Armed Forces Bank)" },
    AppSignature { name: "Bank of America", domain_id: "fintech_banking", subcategory: "bofa", keywords: &["bankofamerica.com", "bofa.com"], category_title: "Commercial Bank (Bank of America)" },
    AppSignature { name: "Wells Fargo", domain_id: "fintech_banking", subcategory: "wells_fargo", keywords: &["wellsfargo.com"], category_title: "Commercial Bank (Wells Fargo)" },
    AppSignature { name: "Citibank", domain_id: "fintech_banking", subcategory: "citi", keywords: &["citi.com", "citibank.com"], category_title: "Commercial Bank (Citibank)" },
    AppSignature { name: "Capital One", domain_id: "fintech_banking", subcategory: "capital_one", keywords: &["capitalone.com"], category_title: "Commercial Bank (Capital One)" },
    AppSignature { name: "PNC Bank", domain_id: "fintech_banking", subcategory: "pnc", keywords: &["pnc.com"], category_title: "Commercial Bank (PNC Bank)" },
    AppSignature { name: "ApexPay", domain_id: "fintech_banking", subcategory: "apexpay", keywords: &["apexpay.org"], category_title: "Payment Platform (ApexPay)" },
    AppSignature { name: "Paybis Crypto", domain_id: "crypto_platforms", subcategory: "paybis", keywords: &["paybis.com"], category_title: "Crypto Exchange (Paybis)" },
    AppSignature { name: "Zypto Crypto", domain_id: "crypto_platforms", subcategory: "zypto", keywords: &["zypto.com"], category_title: "Crypto Wallet & Pay (Zypto)" },
    AppSignature { name: "CoinCodex", domain_id: "crypto_platforms", subcategory: "coincodex", keywords: &["coincodex.com"], category_title: "Crypto Platform (CoinCodex)" },
    AppSignature { name: "TaxAct / W-2 Taxes", domain_id: "financial", subcategory: "tax_filing", keywords: &["taxact.com", "turbotax.com", "hrblock.com"], category_title: "Tax Filing & IRS (TaxAct)" },
    AppSignature { name: "PayPal", domain_id: "fintech_banking", subcategory: "paypal", keywords: &["paypal.com", "service@paypal"], category_title: "Payment Service (PayPal)" },
    AppSignature { name: "Stripe", domain_id: "fintech_banking", subcategory: "stripe", keywords: &["stripe.com"], category_title: "Payment Gateway (Stripe)" },
    AppSignature { name: "Venmo", domain_id: "fintech_banking", subcategory: "venmo", keywords: &["venmo.com"], category_title: "P2P Payments (Venmo)" },
    AppSignature { name: "Cash App", domain_id: "fintech_banking", subcategory: "cash_app", keywords: &["cash.app", "square.com"], category_title: "P2P Payments (Cash App)" },
    AppSignature { name: "Revolut", domain_id: "fintech_banking", subcategory: "revolut", keywords: &["revolut.com"], category_title: "Digital Bank (Revolut)" },
    AppSignature { name: "Wise", domain_id: "fintech_banking", subcategory: "wise", keywords: &["wise.com", "transferwise.com"], category_title: "Cross-Border Payments (Wise)" },
    AppSignature { name: "Payoneer", domain_id: "fintech_banking", subcategory: "payoneer", keywords: &["payoneer.com"], category_title: "Payment Platform (Payoneer)" },
    AppSignature { name: "Zelle", domain_id: "fintech_banking", subcategory: "zelle", keywords: &["zellepay.com"], category_title: "Bank Network (Zelle)" },
    AppSignature { name: "Robinhood", domain_id: "fintech_banking", subcategory: "robinhood", keywords: &["robinhood.com"], category_title: "Trading App (Robinhood)" },
    AppSignature { name: "eToro", domain_id: "fintech_banking", subcategory: "etoro", keywords: &["etoro.com"], category_title: "Trading Platform (eToro)" },
    AppSignature { name: "Monzo", domain_id: "fintech_banking", subcategory: "monzo", keywords: &["monzo.com"], category_title: "Digital Bank (Monzo)" },
    AppSignature { name: "N26", domain_id: "fintech_banking", subcategory: "n26", keywords: &["n26.com"], category_title: "Digital Bank (N26)" },
    AppSignature { name: "Klarna", domain_id: "fintech_banking", subcategory: "klarna", keywords: &["klarna.com"], category_title: "BNPL Fintech (Klarna)" },
    AppSignature { name: "Western Union", domain_id: "fintech_banking", subcategory: "western_union", keywords: &["westernunion.com"], category_title: "Money Transfer (Western Union)" },

    // 📱 MOBILE & ON-DEMAND APPS
    AppSignature { name: "Uber", domain_id: "mobile_apps", subcategory: "uber", keywords: &["uber.com", "ubereats.com"], category_title: "Ride & Delivery (Uber)" },
    AppSignature { name: "Lyft", domain_id: "mobile_apps", subcategory: "lyft", keywords: &["lyft.com", "lyftmail.com"], category_title: "Rideshare App (Lyft)" },
    AppSignature { name: "DoorDash", domain_id: "mobile_apps", subcategory: "doordash", keywords: &["doordash.com"], category_title: "Food Delivery (DoorDash)" },
    AppSignature { name: "Deliveroo", domain_id: "mobile_apps", subcategory: "deliveroo", keywords: &["deliveroo.co.uk", "deliveroo.com"], category_title: "Food Delivery (Deliveroo)" },
    AppSignature { name: "Instacart", domain_id: "mobile_apps", subcategory: "instacart", keywords: &["instacart.com"], category_title: "Grocery Delivery (Instacart)" },
    AppSignature { name: "Airbnb", domain_id: "mobile_apps", subcategory: "airbnb", keywords: &["airbnb.com", "airbnbmail.com"], category_title: "Lodging Booking (Airbnb)" },
    AppSignature { name: "Booking.com", domain_id: "mobile_apps", subcategory: "booking", keywords: &["booking.com"], category_title: "Travel Booking (Booking.com)" },
    AppSignature { name: "Spotify", domain_id: "mobile_apps", subcategory: "spotify", keywords: &["spotify.com"], category_title: "Music Streaming (Spotify)" },
    AppSignature { name: "Netflix", domain_id: "mobile_apps", subcategory: "netflix", keywords: &["netflix.com"], category_title: "Video Streaming (Netflix)" },
    AppSignature { name: "Disney+", domain_id: "mobile_apps", subcategory: "disney", keywords: &["disneyplus.com", "disneystreaming.com"], category_title: "Streaming (Disney+)" },
    AppSignature { name: "Apple Services", domain_id: "mobile_apps", subcategory: "apple", keywords: &["apple.com", "itunes.com", "icloud.com"], category_title: "Apple Ecosystem (iOS/iCloud)" },
    AppSignature { name: "Google Play", domain_id: "mobile_apps", subcategory: "google_play", keywords: &["play.google.com"], category_title: "App Store (Google Play)" },
    AppSignature { name: "Duolingo", domain_id: "mobile_apps", subcategory: "duolingo", keywords: &["duolingo.com"], category_title: "Language App (Duolingo)" },
    AppSignature { name: "Strava", domain_id: "mobile_apps", subcategory: "strava", keywords: &["strava.com"], category_title: "Fitness GPS (Strava)" },

    // 🛍️ E-COMMERCE & MARKETPLACES
    AppSignature { name: "Amazon", domain_id: "ecommerce_shopping", subcategory: "amazon", keywords: &["amazon.com", "auto-confirm@amazon", "amazon.co.uk", "amazon.de"], category_title: "Marketplace (Amazon)" },
    AppSignature { name: "eBay", domain_id: "ecommerce_shopping", subcategory: "ebay", keywords: &["ebay.com", "ebay.co.uk", "ebay@ebay"], category_title: "Auction & Marketplace (eBay)" },
    AppSignature { name: "AliExpress", domain_id: "ecommerce_shopping", subcategory: "aliexpress", keywords: &["aliexpress.com", "alibaba.com"], category_title: "Marketplace (AliExpress)" },
    AppSignature { name: "Temu", domain_id: "ecommerce_shopping", subcategory: "temu", keywords: &["temu.com", "temu-mail.com"], category_title: "Marketplace (Temu)" },
    AppSignature { name: "Shein", domain_id: "ecommerce_shopping", subcategory: "shein", keywords: &["shein.com"], category_title: "Fast Fashion (Shein)" },
    AppSignature { name: "Etsy", domain_id: "ecommerce_shopping", subcategory: "etsy", keywords: &["etsy.com"], category_title: "Craft Marketplace (Etsy)" },
    AppSignature { name: "Walmart", domain_id: "ecommerce_shopping", subcategory: "walmart", keywords: &["walmart.com"], category_title: "Retail (Walmart)" },
    AppSignature { name: "Vinted", domain_id: "ecommerce_shopping", subcategory: "vinted", keywords: &["vinted.com", "vinted.fr"], category_title: "Resale App (Vinted)" },
    AppSignature { name: "StockX", domain_id: "ecommerce_shopping", subcategory: "stockx", keywords: &["stockx.com"], category_title: "Sneaker/Goods (StockX)" },

    // 🤖 AI, CLOUD & DEVELOPER PLATFORMS
    AppSignature { name: "OpenAI / ChatGPT", domain_id: "ai_cloud_dev", subcategory: "openai", keywords: &["openai.com", "chatgpt.com"], category_title: "AI Platform (OpenAI/ChatGPT)" },
    AppSignature { name: "Anthropic Claude", domain_id: "ai_cloud_dev", subcategory: "anthropic", keywords: &["anthropic.com", "claude.ai"], category_title: "AI Platform (Anthropic/Claude)" },
    AppSignature { name: "Midjourney", domain_id: "ai_cloud_dev", subcategory: "midjourney", keywords: &["midjourney.com"], category_title: "Generative AI (Midjourney)" },
    AppSignature { name: "GitHub", domain_id: "ai_cloud_dev", subcategory: "github", keywords: &["github.com", "notifications@github.com"], category_title: "Code Repository (GitHub)" },
    AppSignature { name: "GitLab", domain_id: "ai_cloud_dev", subcategory: "gitlab", keywords: &["gitlab.com"], category_title: "Code Repository (GitLab)" },
    AppSignature { name: "AWS Cloud", domain_id: "ai_cloud_dev", subcategory: "aws", keywords: &["amazonaws.com", "aws.amazon.com"], category_title: "Cloud Services (AWS)" },
    AppSignature { name: "Google Cloud", domain_id: "ai_cloud_dev", subcategory: "gcp", keywords: &["cloud.google.com"], category_title: "Cloud Services (GCP)" },
    AppSignature { name: "Vercel", domain_id: "ai_cloud_dev", subcategory: "vercel", keywords: &["vercel.com"], category_title: "Cloud Deployment (Vercel)" },
    AppSignature { name: "Cloudflare", domain_id: "ai_cloud_dev", subcategory: "cloudflare", keywords: &["cloudflare.com"], category_title: "Infrastructure (Cloudflare)" },

    // 🛡️ VPNS, ENCRYPTED MAIL & PRIVACY
    AppSignature { name: "ProtonMail", domain_id: "vpns_privacy", subcategory: "proton", keywords: &["proton.me", "protonmail.com", "protonvpn.com"], category_title: "Encrypted Mail (Proton)" },
    AppSignature { name: "Tutanota / Tuta", domain_id: "vpns_privacy", subcategory: "tuta", keywords: &["tuta.com", "tutanota.com"], category_title: "Encrypted Mail (Tuta)" },
    AppSignature { name: "SimpleLogin", domain_id: "vpns_privacy", subcategory: "simplelogin", keywords: &["simplelogin.io", "simplelogin.co"], category_title: "Email Alias (SimpleLogin)" },
    AppSignature { name: "DuckDuckGo", domain_id: "vpns_privacy", subcategory: "duckduckgo", keywords: &["duck.com", "duckduckgo.com"], category_title: "Privacy Relay (DuckDuckGo)" },
    AppSignature { name: "NordVPN", domain_id: "vpns_privacy", subcategory: "nordvpn", keywords: &["nordvpn.com", "nordaccount.com"], category_title: "VPN Service (NordVPN)" },
    AppSignature { name: "ExpressVPN", domain_id: "vpns_privacy", subcategory: "expressvpn", keywords: &["expressvpn.com"], category_title: "VPN Service (ExpressVPN)" },
    AppSignature { name: "Mullvad VPN", domain_id: "vpns_privacy", subcategory: "mullvad", keywords: &["mullvad.net"], category_title: "Anonymous VPN (Mullvad)" },
    AppSignature { name: "1Password", domain_id: "vpns_privacy", subcategory: "onepassword", keywords: &["1password.com"], category_title: "Password Manager (1Password)" },
    AppSignature { name: "Bitwarden", domain_id: "vpns_privacy", subcategory: "bitwarden", keywords: &["bitwarden.com"], category_title: "Password Manager (Bitwarden)" },

    // 🖥️ REMOTE ACCESS & PRODUCTIVITY
    AppSignature { name: "AnyDesk", domain_id: "remote_collab", subcategory: "anydesk", keywords: &["anydesk.com"], category_title: "Remote Desktop (AnyDesk)" },
    AppSignature { name: "TeamViewer", domain_id: "remote_collab", subcategory: "teamviewer", keywords: &["teamviewer.com"], category_title: "Remote Desktop (TeamViewer)" },
    AppSignature { name: "RustDesk", domain_id: "remote_collab", subcategory: "rustdesk", keywords: &["rustdesk.com"], category_title: "Remote Desktop (RustDesk)" },
    AppSignature { name: "Zoom", domain_id: "remote_collab", subcategory: "zoom", keywords: &["zoom.us"], category_title: "Video Meetings (Zoom)" },
    AppSignature { name: "Slack", domain_id: "remote_collab", subcategory: "slack", keywords: &["slack.com", "slackmail.com"], category_title: "Workspace (Slack)" },
    AppSignature { name: "Notion", domain_id: "remote_collab", subcategory: "notion", keywords: &["notion.so"], category_title: "Workspace (Notion)" },
    AppSignature { name: "Dropbox", domain_id: "remote_collab", subcategory: "dropbox", keywords: &["dropbox.com", "dropboxmail.com"], category_title: "Cloud Storage (Dropbox)" },
    AppSignature { name: "Google Drive", domain_id: "remote_collab", subcategory: "gdrive", keywords: &["drive.google.com", "docs.google.com"], category_title: "Cloud Storage (Google Drive)" },
    AppSignature { name: "Microsoft OneDrive", domain_id: "remote_collab", subcategory: "onedrive", keywords: &["onedrive.live.com", "sharepoint.com"], category_title: "Cloud Storage (OneDrive)" },
    AppSignature { name: "Mega.nz", domain_id: "remote_collab", subcategory: "mega", keywords: &["mega.nz", "mega.io"], category_title: "Encrypted Cloud (Mega)" },

    // 🎮 GAMING, ESPORTS & GAMBLING
    AppSignature { name: "Steam", domain_id: "gaming_gambling", subcategory: "steam", keywords: &["steampowered.com", "valvesoftware.com"], category_title: "Gaming Platform (Steam)" },
    AppSignature { name: "Epic Games", domain_id: "gaming_gambling", subcategory: "epic_games", keywords: &["epicgames.com"], category_title: "Gaming Store (Epic Games)" },
    AppSignature { name: "PlayStation", domain_id: "gaming_gambling", subcategory: "playstation", keywords: &["playstation.com", "sony.com"], category_title: "Console Network (PlayStation)" },
    AppSignature { name: "Xbox", domain_id: "gaming_gambling", subcategory: "xbox", keywords: &["xbox.com"], category_title: "Gaming Network (Xbox)" },
    AppSignature { name: "Roblox", domain_id: "gaming_gambling", subcategory: "roblox", keywords: &["roblox.com"], category_title: "Metaverse / Gaming (Roblox)" },
    AppSignature { name: "Stake.com", domain_id: "gaming_gambling", subcategory: "stake", keywords: &["stake.com"], category_title: "Crypto Gambling (Stake.com)" },
    AppSignature { name: "Bet365", domain_id: "gaming_gambling", subcategory: "bet365", keywords: &["bet365.com"], category_title: "Sportsbook (Bet365)" },
];

pub fn extract_domain(email_or_url: &str) -> Option<String> {
    if let Some(pos) = email_or_url.find('@') {
        let domain_part = &email_or_url[pos + 1..];
        let clean = domain_part.trim().trim_matches(|c| c == '>' || c == '<' || c == ' ' || c == ';' || c == ',');
        if clean.contains('.') {
            return Some(clean.to_lowercase());
        }
    }
    None
}
